name: Publish Zeal
on:
  release:
    types: [released]

jobs:
  build-and-publish:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7.x.x
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
          cache: 'pnpm'
          registry-url: 'https://registry.npmjs.org'
      - run: pnpm install --frozen-lockfile --ignore-scripts
      - run: pnpm run build
      - name: Publish
        run: pnpm publish --ignore-scripts
        env:
          NODE_AUTH_TOKEN: ${{ secrets.DEEPSOURCE_BOT_TOKEN }}
